// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxuRTscYpJFjmvpXPyxt2UUwnBDVKplSw',
    appId: '1:445485182670:web:181006ca6fc25d6e136a9f',
    messagingSenderId: '445485182670',
    projectId: 'enchanted-event-hall-99f99',
    authDomain: 'enchanted-event-hall-99f99.firebaseapp.com',
    storageBucket: 'enchanted-event-hall-99f99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2YsmefpaZ09CWGlCK1Dlw7xuFtMenha8',
    appId: '1:445485182670:android:b8946b2b486d2d14136a9f',
    messagingSenderId: '445485182670',
    projectId: 'enchanted-event-hall-99f99',
    storageBucket: 'enchanted-event-hall-99f99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkHArRWIp9FXtQCE2F0GNvboBolHpbWSw',
    appId: '1:445485182670:ios:b98137cf174f5c36136a9f',
    messagingSenderId: '445485182670',
    projectId: 'enchanted-event-hall-99f99',
    storageBucket: 'enchanted-event-hall-99f99.firebasestorage.app',
    iosBundleId: 'com.example.enchantedEventHall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkHArRWIp9FXtQCE2F0GNvboBolHpbWSw',
    appId: '1:445485182670:ios:b98137cf174f5c36136a9f',
    messagingSenderId: '445485182670',
    projectId: 'enchanted-event-hall-99f99',
    storageBucket: 'enchanted-event-hall-99f99.firebasestorage.app',
    iosBundleId: 'com.example.enchantedEventHall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxuRTscYpJFjmvpXPyxt2UUwnBDVKplSw',
    appId: '1:445485182670:web:b54b490d91cfe172136a9f',
    messagingSenderId: '445485182670',
    projectId: 'enchanted-event-hall-99f99',
    authDomain: 'enchanted-event-hall-99f99.firebaseapp.com',
    storageBucket: 'enchanted-event-hall-99f99.firebasestorage.app',
  );
}
